title: 折腾君笔记
author: zhetengjun
email: zhetengjun@qq.com
description: > # this means to ignore newlines until "baseurl:"
  折腾君笔记

# social links
twitter_username: zhetengjun # DO NOT include the @ character, or else the build will fail!
github_username:  zhetengjun # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
